import { DeliveryRouteDisplay } from "./types";

// Dummy data for display (converted from DeliveryRoute format)
export const DUMMY_DISPLAYS: DeliveryRouteDisplay[] = [
  {
    _id: "dummy1",
    pickupStateId: "state1",
    pickupState: "Lagos",
    pickupCityId: "city1",
    pickupCity: "Ikeja",
    destStateId: "state1",
    destState: "Lagos",
    destCityId: "city2",
    destCity: "Lekki",
    baseFee: 2300,
    multiplier: 0,
  },
  {
    _id: "dummy2",
    pickupStateId: "state1",
    pickupState: "Lagos",
    pickupCityId: "city1",
    pickupCity: "Ikeja",
    destStateId: "state1",
    destState: "Lagos",
    destCityId: "city3",
    destCity: "Victoria Island",
    baseFee: 4300,
    multiplier: 0,
  },
  {
    _id: "dummy3",
    pickupStateId: "state2",
    pickupState: "Abuja FCT",
    pickupCityId: "city4",
    pickupCity: "Garki",
    destStateId: "state1",
    destState: "Lagos",
    destCityId: "city1",
    destCity: "Ikeja",
    baseFee: 3000,
    multiplier: 2,
  },
  {
    _id: "dummy4",
    pickupStateId: "state1",
    pickupState: "Lagos",
    pickupCityId: "city1",
    pickupCity: "Ikeja",
    destStateId: "state1",
    destState: "Lagos",
    destCityId: "city2",
    destCity: "Lekki",
    baseFee: 2300,
    multiplier: 0,
  },
  {
    _id: "dummy5",
    pickupStateId: "state2",
    pickupState: "Abuja FCT",
    pickupCityId: "city4",
    pickupCity: "Garki",
    destStateId: "state1",
    destState: "Lagos",
    destCityId: "city1",
    destCity: "Ikeja",
    baseFee: 3000,
    multiplier: 2,
  },
  {
    _id: "dummy6",
    pickupStateId: "state1",
    pickupState: "Lagos",
    pickupCityId: "city1",
    pickupCity: "Ikeja",
    destStateId: "state1",
    destState: "Lagos",
    destCityId: "city3",
    destCity: "Victoria Island",
    baseFee: 2300,
    multiplier: 0,
  },
];
