export const nigerianStates = [
  { label: "Abia", value: "abia", cities: ["Umuahia", "Aba", "Ohafia", "Arochukwu", "Bende"] },
  { label: "Adamawa", value: "adamawa", cities: ["Yola", "Mubi", "Jimeta", "Numan", "Ganye"] },
  { label: "Akwa Ibom", value: "akwa-ibom", cities: ["Uyo", "Ikot Ekpene", "Eket", "Oron", "Abak"] },
  { label: "Anambra", value: "anambra", cities: ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Obosi"] },
  { label: "Bauchi", value: "bauchi", cities: ["Bauchi", "Azare", "Misau", "Jama'are", "Darazo"] },
  { label: "Bayelsa", value: "bayelsa", cities: ["Yenagoa", "Brass", "Ogbia", "Sagbama", "Ekeremor"] },
  { label: "Benue", value: "benue", cities: ["Makurdi", "Otukpo", "Gboko", "Katsina-Ala", "Vandeikya"] },
  { label: "Borno", value: "borno", cities: ["Maiduguri", "Biu", "Dikwa", "Monguno", "Kaga"] },
  { label: "Cross River", value: "cross-river", cities: ["Calabar", "Ikom", "Ogoja", "Ugep", "Obudu"] },
  { label: "Delta", value: "delta", cities: ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor"] },
  { label: "Ebonyi", value: "ebonyi", cities: ["Abakaliki", "Afikpo", "Onueke", "Ezza", "Ishielu"] },
  { label: "Edo", value: "edo", cities: ["Benin City", "Auchi", "Ekpoma", "Irrua", "Uromi"] },
  { label: "Ekiti", value: "ekiti", cities: ["Ado Ekiti", "Ikere", "Ilawe", "Omuo", "Iyin Ekiti"] },
  { label: "Enugu", value: "enugu", cities: ["Enugu", "Nsukka", "Awgu", "Agbani", "Udi"] },
  { label: "Gombe", value: "gombe", cities: ["Gombe", "Kaltungo", "Billiri", "Dukku", "Nafada"] },
  { label: "Imo", value: "imo", cities: ["Owerri", "Orlu", "Okigwe", "Oguta", "Mbaise"] },
  { label: "Jigawa", value: "jigawa", cities: ["Dutse", "Hadejia", "Gumel", "Kazaure", "Birnin Kudu"] },
  { label: "Kaduna", value: "kaduna", cities: ["Kaduna", "Zaria", "Kafanchan", "Soba", "Birnin Gwari"] },
  { label: "Kano", value: "kano", cities: ["Kano", "Wudil", "Gaya", "Bichi", "Dambatta"] },
  { label: "Katsina", value: "katsina", cities: ["Katsina", "Daura", "Funtua", "Malumfashi", "Dutsin-Ma"] },
  { label: "Kebbi", value: "kebbi", cities: ["Birnin Kebbi", "Argungu", "Zuru", "Yauri", "Jega"] },
  { label: "Kogi", value: "kogi", cities: ["Lokoja", "Okene", "Idah", "Anyigba", "Kabba"] },
  { label: "Kwara", value: "kwara", cities: ["Ilorin", "Offa", "Omu-Aran", "Lafiagi", "Patigi"] },
  { label: "Lagos", value: "lagos", cities: ["Ikeja", "Lekki", "Ikorodu", "Epe", "Badagry"] },
  { label: "Nasarawa", value: "nasarawa", cities: ["Lafia", "Keffi", "Akwanga", "Doma", "Nasarawa"] },
  { label: "Niger", value: "niger", cities: ["Minna", "Suleja", "Bida", "Kontagora", "Mokwa"] },
  { label: "Ogun", value: "ogun", cities: ["Abeokuta", "Ijebu-Ode", "Sango Ota", "Ilaro", "Sagamu"] },
  { label: "Ondo", value: "ondo", cities: ["Akure", "Ondo", "Owo", "Okitipupa", "Ikare"] },
  { label: "Osun", value: "osun", cities: ["Oshogbo", "Ife", "Ilesa", "Ikirun", "Ejigbo"] },
  { label: "Oyo", value: "oyo", cities: ["Ibadan", "Ogbomosho", "Oyo", "Iseyin", "Saki"] },
  { label: "Plateau", value: "plateau", cities: ["Jos", "Barkin Ladi", "Pankshin", "Shendam", "Langtang"] },
  { label: "Rivers", value: "rivers", cities: ["Port Harcourt", "Bonny", "Omoku", "Okrika", "Ahoada"] },
  { label: "Sokoto", value: "sokoto", cities: ["Sokoto", "Tambuwal", "Gwadabawa", "Wurno", "Illela"] },
  { label: "Taraba", value: "taraba", cities: ["Jalingo", "Wukari", "Bali", "Takum", "Serti"] },
  { label: "Yobe", value: "yobe", cities: ["Damaturu", "Potiskum", "Nguru", "Gashua", "Geidam"] },
  { label: "Zamfara", value: "zamfara", cities: ["Gusau", "Kaura Namoda", "Anka", "Talata Mafara", "Gummi"] },
  { label: "FCT - Abuja", value: "fct", cities: ["Abuja", "Gwagwalada", "Kubwa", "Kuje", "Bwari"] }
];










// export const nigerianstates = [
//     { label: "Abia", value: "abia" },
//     { label: "Adamawa", value: "adamawa" },
//     { label: "Akwa Ibom", value: "akwa_ibom" },
//     { label: "Anambra", value: "anambra" },
//     { label: "Bauchi", value: "bauchi" },
//     { label: "Bayelsa", value: "bayelsa" },
//     { label: "Benue", value: "benue" },
//     { label: "Borno", value: "borno" },
//     { label: "Cross River", value: "cross_river" },
//     { label: "Delta", value: "delta" },
//     { label: "Ebonyi", value: "ebonyi" },
//     { label: "Edo", value: "edo" },
//     { label: "Ekiti", value: "ekiti" },
//     { label: "Enugu", value: "enugu" },
//     { label: "Gombe", value: "gombe" },
//     { label: "Imo", value: "imo" },
//     { label: "Jigawa", value: "jigawa" },
//     { label: "Kaduna", value: "kaduna" },
//     { label: "Kano", value: "kano" },
//     { label: "Katsina", value: "katsina" },
//     { label: "Kebbi", value: "kebbi" },
//     { label: "Kogi", value: "kogi" },
//     { label: "Kwara", value: "kwara" },
//     { label: "Lagos", value: "lagos" },
//     { label: "Nasarawa", value: "nasarawa" },
//     { label: "Niger", value: "niger" },
//     { label: "Ogun", value: "ogun" },
//     { label: "Ondo", value: "ondo" },
//     { label: "Osun", value: "osun" },
//     { label: "Oyo", value: "oyo" },
//     { label: "Plateau", value: "plateau" },
//     { label: "Rivers", value: "rivers" },
//     { label: "Sokoto", value: "sokoto" },
//     { label: "Taraba", value: "taraba" },
//     { label: "Yobe", value: "yobe" },
//     { label: "Zamfara", value: "zamfara" },
//   ];
  
//   export const nigeriancities = [
//     { label: "Abraka", value: "Abraka" },
//     { label: "Abuja", value: "Abuja" },
//     { label: "Aba", value: "Aba" },
//     { label: "Abakaliki", value: "Abakaliki" },
//     { label: "Abeokuta", value: "Abeokuta" },
//     { label: "Ado-Ekiti", value: "Ado-Ekiti" },
//     { label: "Adani", value: "Adani" },
//     { label: "Ado", value: "Ado" },
//     { label: "Agbor", value: "Agbor" },
//     { label: "Agege", value: "Agege" },
//     { label: "Agidingbi", value: "Agidingbi" },
//     { label: "Ajegunle", value: "Ajegunle" },
//     { label: "Ajuwon", value: "Ajuwon" },
//     { label: "Akaeze", value: "Akaeze" },
//     { label: "Aku", value: "Aku" },
//     { label: "Akwete", value: "Akwete" },
//     { label: "Alimosho", value: "Alimosho" },
//     { label: "Aluu", value: "Aluu" },
//     { label: "Amagunze", value: "Amagunze" },
//     { label: "Amassoma", value: "Amassoma" },
//     { label: "Anambra", value: "Anambra" },
//     { label: "Apapa", value: "Apapa" },
//     { label: "Argungu", value: "Argungu" },
//     { label: "Asaba", value: "Asaba" },
//     { label: "Awka", value: "Awka" },
//     { label: "Ayobo", value: "Ayobo" },
//     { label: "Azare", value: "Azare" },
//     { label: "Babana", value: "Babana" },
//     { label: "Badagry", value: "Badagry" },
//     { label: "Bagudo", value: "Bagudo" },
//     { label: "Bara", value: "Bara" },
//     { label: "Bende", value: "Bende" },
//     { label: "Benin City", value: "Benin City" },
//     { label: "Benisheikh", value: "Benisheikh" },
//     { label: "Biase", value: "Biase" },
//     { label: "Bida", value: "Bida" },
//     { label: "Birnin Kebbi", value: "Birnin Kebbi" },
//     { label: "Biu", value: "Biu" },
//     { label: "Boi", value: "Boi" },
//     { label: "Bonny", value: "Bonny" },
//     { label: "Boripe", value: "Boripe" },
//     { label: "Borno", value: "Borno" },
//     { label: "Bosso", value: "Bosso" },
//     { label: "Bwari", value: "Bwari" },
//     { label: "Burutu", value: "Burutu" },
//     { label: "Calabar", value: "Calabar" },
//     { label: "Chafe", value: "Chafe" },
//     { label: "Damboa", value: "Damboa" },
//     { label: "Damaturu", value: "Damaturu" },
//     { label: "Dangora", value: "Dangora" },
//     { label: "Dangote", value: "Dangote" },
//     { label: "Dekina", value: "Dekina" },
//     { label: "Denge Shuni", value: "Denge Shuni" },
//     { label: "Dikwa", value: "Dikwa" },
//     { label: "Doma", value: "Doma" },
//     { label: "Dutsen Wai", value: "Dutsen Wai" },
//     { label: "Dutsin-Ma", value: "Dutsin-Ma" },
//     { label: "Dutse", value: "Dutse" },
//     { label: "Ebute Ikorodu", value: "Ebute Ikorodu" },
//     { label: "Ede", value: "Ede" },
//     { label: "Efon-Alaaye", value: "Efon-Alaaye" },
//     { label: "Eha Amufu", value: "Eha Amufu" },
//     { label: "Eket", value: "Eket" },
//     { label: "Ekpoma", value: "Ekpoma" },
//     { label: "Ela", value: "Ela" },
//     { label: "Elele", value: "Elele" },
//     { label: "Elesha", value: "Elesha" },
//     { label: "Emure-Ekiti", value: "Emure-Ekiti" },
//     { label: "Enugu-Ezike", value: "Enugu-Ezike" },
//     { label: "Esuk Oron", value: "Esuk Oron" },
//     { label: "Ezza-Ohu", value: "Ezza-Ohu" },
//     { label: "Festac Town", value: "Festac Town" },
//     { label: "Forum", value: "Forum" },
//     { label: "Funtua", value: "Funtua" },
//     { label: "Gakem", value: "Gakem" },
//     { label: "Ganye", value: "Ganye" },
//     { label: "Gashaka", value: "Gashaka" },
//     { label: "Gashua", value: "Gashua" },
//     { label: "Gbagada", value: "Gbagada" },
//     { label: "Gbongan", value: "Gbongan" },
//     { label: "Gombi", value: "Gombi" },
//     { label: "Gumel", value: "Gumel" },
//     { label: "Gusau", value: "Gusau" },
//     { label: "Gwagwalada", value: "Gwagwalada" },
//     { label: "Gwarzo", value: "Gwarzo" },
//     { label: "Gwoza", value: "Gwoza" },
//     { label: "Hadejia", value: "Hadejia" },
//     { label: "Holma", value: "Holma" },
//     { label: "Ibadan", value: "Ibadan" },
//     { label: "Ibaji", value: "Ibaji" },
//     { label: "Iberekodo", value: "Iberekodo" },
//     { label: "Ibeto", value: "Ibeto" },
//     { label: "Ido", value: "Ido" },
//     { label: "Idoani", value: "Idoani" },
//     { label: "Ido-Osi", value: "Ido-Osi" },
//     { label: "Igbor", value: "Igbor" },
//     { label: "Igboho", value: "Igboho" },
//     { label: "Igbo-Ukwu", value: "Igbo-Ukwu" },
//     { label: "Igede-Ekiti", value: "Igede-Ekiti" },
//     { label: "Ihiala", value: "Ihiala" },
//     { label: "Ijebu-Ife", value: "Ijebu-Ife" },
//     { label: "Ijebu-Igbo", value: "Ijebu-Igbo" },
//     { label: "Ijebu-Jesa", value: "Ijebu-Jesa" },
//     { label: "Ijebu-Ode", value: "Ijebu-Ode" },
//     { label: "Ijero-Ekiti", value: "Ijero-Ekiti" },
//     { label: "Ijora", value: "Ijora" },
//     { label: "Iju", value: "Iju" },
//     { label: "Ikang", value: "Ikang" },
//     { label: "Ikeja", value: "Ikeja" },
//     { label: "Ikere-Ekiti", value: "Ikere-Ekiti" },
//     { label: "Ikire", value: "Ikire" },
//     { label: "Ikirun", value: "Ikirun" },
//     { label: "Ikorodu", value: "Ikorodu" },
//     { label: "Ikot Ekpene", value: "Ikot Ekpene" },
//     { label: "Ikotun", value: "Ikotun" },
//     { label: "Ila Orangun", value: "Ila Orangun" },
//     { label: "Ile-Ife", value: "Ile-Ife" },
//     { label: "Ilesa", value: "Ilesa" },
//     { label: "Ilisan", value: "Ilisan" },
//     { label: "Ilaro", value: "Ilaro" },
//     { label: "Ilashe", value: "Ilashe" },
//     { label: "Ilobu", value: "Ilobu" },
//     { label: "Ilorin", value: "Ilorin" },
//     { label: "Imeko", value: "Imeko" },
//     { label: "Inisa", value: "Inisa" },
//     { label: "Isara", value: "Isara" },
//     { label: "Ise-Ekiti", value: "Ise-Ekiti" },
//     { label: "Isieke", value: "Isieke" },
//     { label: "Ita Ogbolu", value: "Ita Ogbolu" },
//     { label: "Itas Gadau", value: "Itas Gadau" },
//     { label: "Itire", value: "Itire" },
//     { label: "Iwo", value: "Iwo" },
//     { label: "Jabi", value: "Jabi" },
//     { label: "Jakusko", value: "Jakusko" },
//     { label: "Jalingo", value: "Jalingo" },
//     { label: "Jimeta", value: "Jimeta" },
//     { label: "Jos", value: "Jos" },
//     { label: "Kabba", value: "Kabba" },
//     { label: "Kaduna", value: "Kaduna" },
//     { label: "Kafachan", value: "Kafachan" },
//     { label: "Kafin Hausa", value: "Kafin Hausa" },
//     { label: "Kagara", value: "Kagara" },
//     { label: "Kaiama", value: "Kaiama" },
//     { label: "Kajuru", value: "Kajuru" },
//     { label: "Kaltungo", value: "Kaltungo" },
//     { label: "Kamba", value: "Kamba" },
//     { label: "Kano", value: "Kano" },
//     { label: "Karu", value: "Karu" },
//     { label: "Katcha", value: "Katcha" },
//     { label: "Katsina", value: "Katsina" },
//     { label: "Keffi", value: "Keffi" },
//     { label: "Ketu", value: "Ketu" },
//     { label: "Kishi", value: "Kishi" },
//     { label: "Kiyawa", value: "Kiyawa" },
//     { label: "Koko", value: "Koko" },
//     { label: "Kontagora", value: "Kontagora" },
//     { label: "Koton Karfe", value: "Koton Karfe" },
//     { label: "Kuje", value: "Kuje" },
//     { label: "Kukawa", value: "Kukawa" },
//     { label: "Kumo", value: "Kumo" },
//     { label: "Kunchi", value: "Kunchi" },
//     { label: "Kura", value: "Kura" },
//     { label: "Kuta", value: "Kuta" },
//     { label: "Kwale", value: "Kwale" },
//     { label: "Kwalla", value: "Kwalla" },
//     { label: "Kwami", value: "Kwami" },
//     { label: "Kwara", value: "Kwara" },
//     { label: "Lafia", value: "Lafia" },
//     { label: "Lafiagi", value: "Lafiagi" },
//     { label: "Lagelu", value: "Lagelu" },
//     { label: "Lagos", value: "Lagos" },
//     { label: "Lapai", value: "Lapai" },
//     { label: "Lekki", value: "Lekki" },
//     { label: "Lere", value: "Lere" },
//     { label: "Lokoja", value: "Lokoja" },
//     { label: "Makurdi", value: "Makurdi" },
//     { label: "Malumfashi", value: "Malumfashi" },
//     { label: "Mararaba", value: "Mararaba" },
//     { label: "Mayo-Belwa", value: "Mayo-Belwa" },
//     { label: "Mgbidi", value: "Mgbidi" },
//     { label: "Minna", value: "Minna" },
//     { label: "Mopa", value: "Mopa" },
//     { label: "Moriki", value: "Moriki" },
//     { label: "Nasarawa", value: "Nasarawa" },
//     { label: "Nguru", value: "Nguru" },
//     { label: "Nkwo Nnewi", value: "Nkwo Nnewi" },
//     { label: "Nkwo-Okija", value: "Nkwo-Okija" },
//     { label: "Nnewi", value: "Nnewi" },
//     { label: "Nnewi-Ichi", value: "Nnewi-Ichi" },
//     { label: "Nsukka", value: "Nsukka" },
//     { label: "Obalende", value: "Obalende" },
//     { label: "Obi Ngwa", value: "Obi Ngwa" },
//     { label: "Obollo-Afor", value: "Obollo-Afor" },
//     { label: "Obosi", value: "Obosi" },
//     { label: "Obubra", value: "Obubra" },
//     { label: "Ode", value: "Ode" },
//     { label: "Ode-Aye", value: "Ode-Aye" },
//     { label: "Odeda", value: "Odeda" },
//     { label: "Ode-Irele", value: "Ode-Irele" },
//     { label: "Ode-Omu", value: "Ode-Omu" },
//     { label: "Odi-Olowo", value: "Odi-Olowo" },
//     { label: "Ogbaku", value: "Ogbaku" },
//     { label: "Ogbomosho", value: "Ogbomosho" },
//     { label: "Ogijo", value: "Ogijo" },
//     { label: "Ogudu", value: "Ogudu" },
//     { label: "Ogui", value: "Ogui" },
//     { label: "Ogun", value: "Ogun" },
//     { label: "Oguta", value: "Oguta" },
//     { label: "Ogwashi-Uku", value: "Ogwashi-Uku" },
//     { label: "Ojodu", value: "Ojodu" },
//     { label: "Ojoto", value: "Ojoto" },
//     { label: "Oju", value: "Oju" },
//     { label: "Oju Olobun", value: "Oju Olobun" },
//     { label: "Oka", value: "Oka" },
//     { label: "Okigwe", value: "Okigwe" },
//     { label: "Okitipupa", value: "Okitipupa" },
//     { label: "Oko", value: "Oko" },
//     { label: "Oko-Oba", value: "Oko-Oba" },
//     { label: "Okpoko", value: "Okpoko" },
//     { label: "Okposi", value: "Okposi" },
//     { label: "Okrika", value: "Okrika" },
//     { label: "Ola", value: "Ola" },
//     { label: "Olodo", value: "Olodo" },
//     { label: "Ondo", value: "Ondo" },
//     { label: "Onitsha", value: "Onitsha" },
//     { label: "Onueke", value: "Onueke" },
//     { label: "Onuiyi", value: "Onuiyi" },
//     { label: "Opobo", value: "Opobo" },
//     { label: "Orerokpe", value: "Orerokpe" },
//     { label: "Orita Eruwa", value: "Orita Eruwa" },
//     { label: "Orogun", value: "Orogun" },
//     { label: "Oron", value: "Oron" },
//     { label: "Oru", value: "Oru" },
//     { label: "Oshogbo", value: "Oshogbo" },
//     { label: "Ota", value: "Ota" },
//     { label: "Otukpo", value: "Otukpo" },
//     { label: "Owerri", value: "Owerri" },
//     { label: "Owo", value: "Owo" },
//     { label: "Oyo", value: "Oyo" },
//     { label: "Oyoko", value: "Oyoko" },
//     { label: "Ozubulu", value: "Ozubulu" },
//     { label: "Pategi", value: "Pategi" },
//     { label: "Port Harcourt", value: "Port Harcourt" },
//     { label: "Potiskum", value: "Potiskum" },
//     { label: "Rumuosi", value: "Rumuosi" },
//     { label: "Sabo Gari", value: "Sabo Gari" },
//     { label: "Sagamu", value: "Sagamu" },
//     { label: "Sapele", value: "Sapele" },
//     { label: "Shagamu", value: "Shagamu" },
//     { label: "Shagari", value: "Shagari" },
//     { label: "Shendam", value: "Shendam" },
//     { label: "Sokoto", value: "Sokoto" },
//     { label: "Suleja", value: "Suleja" },
//     { label: "Suru", value: "Suru" },
//     { label: "Tambuwal", value: "Tambuwal" },
//     { label: "Tarauni", value: "Tarauni" },
//     { label: "Tegina", value: "Tegina" },
//     { label: "Tsafe", value: "Tsafe" },
//     { label: "Ubiaja", value: "Ubiaja" },
//     { label: "Ubima", value: "Ubima" },
//     { label: "Udi", value: "Udi" },
//     { label: "Ughelli", value: "Ughelli" },
//     { label: "Ugwolawo", value: "Ugwolawo" },
//     { label: "Umuahia", value: "Umuahia" },
//     { label: "Uromi", value: "Uromi" },
//     { label: "Urualla", value: "Urualla" },
//     { label: "Uyo", value: "Uyo" },
//     { label: "Uzuakoli", value: "Uzuakoli" },
//     { label: "Vandeikya", value: "Vandeikya" },
//     { label: "Victoria Island", value: "Victoria Island" },
//     { label: "Wamba", value: "Wamba" },
//     { label: "Warri", value: "Warri" },
//     { label: "Wudil", value: "Wudil" },
//     { label: "Wukari", value: "Wukari" },
//     { label: "Wuse", value: "Wuse" },
//     { label: "Wushishi", value: "Wushishi" },
//     { label: "Yaba", value: "Yaba" },
//     { label: "Yankaba", value: "Yankaba" },
//     { label: "Yenagoa", value: "Yenagoa" },
//     { label: "Yola", value: "Yola" },
//     { label: "Zakibiam", value: "Zakibiam" },
//     { label: "Zamfara", value: "Zamfara" },
//     { label: "Zaria", value: "Zaria" },
//     { label: "Zuba", value: "Zuba" },
//   ];